import { RandomProps, getRandomNumber } from "@/src/services/getRandomNumber";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const [randomizerProps, setRandomizerProps] = useState<RandomProps>({
    numbers: 1,
    min: 1,
    max: 2,
  });
  const [randomizedNumber, setRandomizedNumber] = useState([0]);
  const [randomize, setRandomize] = useState(false);
  useEffect(() => {
    if (randomize) {
      getRandomNumber(randomizerProps).then((res) => {
        setRandomizedNumber(res);
      });
      setRandomize(false);
    }
  }, [randomize, randomizerProps]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div
          style={{
            display: "flex",
            flexDirection: "column",
            gap: "5px",
            alignItems: "center",
            marginTop: "20px",
          }}
        >
          <label>Qtd numeros:</label>
          <input
            type="number"
            style={{ width: "100px", height: "30px" }}
            onChange={(e) =>
              setRandomizerProps({
                ...randomizerProps,
                numbers: parseInt(e.target.value),
              })
            }
          />
          <label>Min:</label>
          <input
            style={{ width: "100px", height: "30px" }}
            onChange={(e) =>
              setRandomizerProps({
                ...randomizerProps,
                min: parseInt(e.target.value),
              })
            }
          />
          <label>Max:</label>
          <input
            style={{ width: "100px", height: "30px" }}
            onChange={(e) =>
              setRandomizerProps({
                ...randomizerProps,
                max: parseInt(e.target.value),
              })
            }
          />
          <button
            onClick={() => setRandomize(true)}
            style={{ width: "100px", height: "30px" }}
          >
            RANDOMIZE
          </button>
          <p style={{ marginTop: "40px", fontSize: "25px", color: "#F1B1C5" }}>
            {randomizedNumber}
          </p>
        </div>
      </main>
    </>
  );
}
